title: "AIMS Research Group"
description: "University of Wisconsin - Eau Claire, Computer Science Department Research in Artificial Intelligence, Machine Learning, and Security"
baseurl: ""
theme: minima

plugins:
  - jekyll-feed
